#!/bin/bash

echo "🚀 Quick Render Deployment Guide"
echo "================================"
echo ""
echo "Your backend is ready for deployment!"
echo ""
echo "📋 Follow these steps:"
echo ""
echo "1. Go to https://render.com and sign up"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Upload the 'backend' folder from your project"
echo "4. Set these environment variables:"
echo "   - NODE_ENV=production"
echo "   - MONGODB_URI=mongodb+srv://moon:947131@cluster0.gvga3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
echo "   - DB_NAME=test"
echo "   - JWT_SECRET=trendhive-secret-key-2024"
echo "5. Set Build Command: npm install"
echo "6. Set Start Command: npm start"
echo "7. Deploy and get your URL"
echo ""
echo "🔗 After deployment, update src/config/api.js with your URL"
echo ""
echo "📱 Then build your APK: npx eas build --platform android --profile production"
echo ""
echo "✅ Your app will work independently!" 